import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";


const spaceGrotesk = Space_Grotesk({
  variable: '--font-space-grotesk',
  subsets: ['latin']
})


export const metadata: Metadata = {
  title: "Curso Academia - Next.js",
  description: "Generated by create next app",
};

/**
 * Application root layout that provides the HTML scaffold and global styling for all pages.
 *
 * Renders an `<html lang="en">` and `<body>` that apply the configured Space Grotesk font and antialiasing, and wraps `children` inside a `<main>` container.
 *
 * @param children - The page content to render inside the root layout
 * @returns The root HTML element containing the provided `children`
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${spaceGrotesk.className} antialiased`}>
        <main className='flex-1'>{children}</main>
      </body>
    </html>
  );
}